// Do not edit. This file is machine generated by the Resource DLL Wizard.

library TesteLang;

{ITE} {DFMFileType} {uTesteLang.dfm}
{ITE} {RCFileType} {Win32\Debug\TesteLang_DRC.rc}

{$R 'uTesteLang.dfm' 'Form4:TForm'}
{$R 'Win32\Debug\TesteLang_DRC.res' 'Win32\Debug\TesteLang_DRC.rc'}

{$E ENU}

begin
end.
