unit ncMWFileServer;

// =========================================================================
// kbmMW - An advanced and extendable middleware framework.
// by Components4Developers (http://www.components4developers.com)
//
// Service generated by kbmMW service wizard.
//
// INSTRUCTIONS FOR REGISTRATION/USAGE
// -----------------------------------
// Please update the uses clause of the datamodule/form the TkbmMWServer is placed on by adding kbmMWFileService 
// to it. Eg.
// 
//     uses ...,kbmMWServer,kbmMWFileService;
// 
// Somewhere in your application, make sure to register the serviceclass to the TkbmMWServer instance. Eg.
// 
// var
//    sd:TkbmMWCustomServiceDefinition;
// ..
//    sd:=kbmMWServer1.RegisterService(yourserviceclassname,false);
// 
// Set the last parameter to true if this is the default service.
// 
// 
// SPECIFIC FILE SERVICE REGISTRATION INSTRUCTIONS
// -----------------------------------------------
// Cast the returned service definition object (sd) to a TkbmMWFileServiceDefinition. eg:
// 
// var
//    fsd:TkbmMWFileServiceDefinition;
// ..
//    fsd:=TkbmMWFileServiceDefinition(sd)
//    fsd.RootPath:='NexCafe\Atualiza';
//    fsd.BlockSize:=8192;
//    fsd.ListAttributesOptional:=false;
//    fsd.ListAttributes:=faReadOnly+faDirectory+faArchive;
//    fsd.StorageAttributes:=faArchive;
// -----------------------------------------------



{$I kbmMW.inc}

interface

uses
  SysUtils, {$ifdef LEVEL6}Variants{$else}Forms{$endif}, Classes, kbmMWSecurity, kbmMWServer, kbmMWGlobal, kbmMWFileService;

type
  TmwFileServer = class(TkbmMWFileService)
    procedure kbmMWFileServiceFileAccess(Sender: TObject; Path: string;
      var AccessPermissions: TkbmMWFileAccessPermissions);
    procedure kbmMWFileServiceAuthenticate(Sender: TObject;
      ClientIdent: TkbmMWClientIdentity; var Perm: TkbmMWAccessPermissions);
  private
     { Private declarations }
  protected
     { Private declarations }
  public
     { Public declarations }
{$IFNDEF CPP}class{$ENDIF} function GetPrefServiceName:string; override;
{$IFNDEF CPP}class{$ENDIF} function GetFlags:TkbmMWServiceFlags; override;
  end;

implementation

uses ncMWServer;

{$R *.dfm}


// Service definitions.
//---------------------

{$IFNDEF CPP}class{$ENDIF} function TmwFileServer.GetPrefServiceName:string;
begin
     Result:='NexCafeFileServer';
end;

procedure TmwFileServer.kbmMWFileServiceAuthenticate(Sender: TObject;
  ClientIdent: TkbmMWClientIdentity; var Perm: TkbmMWAccessPermissions);
begin
  inherited;
  Perm := [mwapRead];
end;

procedure TmwFileServer.kbmMWFileServiceFileAccess(Sender: TObject;
  Path: string; var AccessPermissions: TkbmMWFileAccessPermissions);
begin
  inherited;
  AccessPermissions := [mwfapGet, mwfapPut];
end;

{$IFNDEF CPP}class{$ENDIF} function TmwFileServer.GetFlags:TkbmMWServiceFlags;
begin
     Result:=[mwsfListed];
end;


end.