program NexAdmin_Loja;

uses
  ncaCurrFormat in '..\ncaCurrFormat.pas',
  Forms,
  ncaFrmPri in 'ncaFrmPri.pas' {FrmPri},
  ncaDM in '..\ncaDM.pas' {Dados: TDataModule},
  ufmImagens in '..\..\..\FormMgr\ufmImagens.pas' {dmImagens: TDataModule},
  ufmFormBase in '..\..\..\FormMgr\ufmFormBase.pas' {FrmBase: TFrmBasePai},
  ncaFrmLogin in '..\ncaFrmLogin.pas' {FrmLogin},
  ncafbTran in '..\ncafbTran.pas' {fbTran: TFrmBasePai},
  ncaFrmTipos in '..\ncaFrmTipos.pas' {FrmTipos},
  ncafbCartoes in '..\ncafbCartoes.pas' {fbCartoes: TFrmBasePai},
  ncAuxPassaporte in '..\..\Comp\ncAuxPassaporte.pas',
  ncaFrmCadFornecedor in '..\ncaFrmCadFornecedor.pas' {FrmCadFornecedor},
  ncafbPesqCH in '..\ncafbPesqCH.pas' {fbPesqCH: TFrmBasePai},
  ncafbProdutos in '..\ncafbProdutos.pas' {fbProdutos: TFrmBasePai},
  ncafgExtratoFid in '..\ncafgExtratoFid.pas' {fbExtratoFid: TFrmBasePai},
  ncaFrmUsuario in '..\ncaFrmUsuario.pas' {FrmUsuario},
  ncaFrmSenhaWiz in '..\ncaFrmSenhaWiz.pas' {FrmSenhaWiz},
  ncafbCaixa in '..\ncafbCaixa.pas' {fbCaixa: TFrmBasePai},
  ncaFrmPass in '..\ncaFrmPass.pas' {FrmPassaporte},
  ncafbCaixasA in '..\ncafbCaixasA.pas' {fbCaixasA: TFrmBasePai},
  ncaFrmCaixa in '..\ncaFrmCaixa.pas' {FrmCaixa},
  ncafbOpcoes in '..\ncafbOpcoes.pas' {fbOpcoes: TFrmBasePai},
  ncafbTiposImp in '..\ncafbTiposImp.pas' {fbTiposImp: TFrmBasePai},
  ncafbTipoPass in '..\ncafbTipoPass.pas' {fbTiposPass: TFrmBasePai},
  ncafbTarBasica in '..\ncafbTarBasica.pas' {fbTarBasica: TFrmBasePai},
  ncaFrmTipoImp in '..\ncaFrmTipoImp.pas' {FrmTipoImp},
  ncafbUsuarios in '..\ncafbUsuarios.pas' {fbUsuarios: TFrmBasePai},
  ncaFrmCaptura in '..\ncaFrmCaptura.pas' {FrmCapt},
  ncaFrmImpEtqCli in '..\ncaFrmImpEtqCli.pas' {FrmImpEtqCli},
  ncaFrmAjustaFid in '..\ncaFrmAjustaFid.pas' {FrmAjustaFid},
  ncaFrmContato in '..\ncaFrmContato.pas' {FrmContato},
  ncaFrmHistVer in '..\ncaFrmHistVer.pas' {FrmRTF},
  ncafbPacotes in '..\ncafbPacotes.pas' {fbPacotes: TFrmBasePai},
  ncaFrmPatro in '..\ncaFrmPatro.pas' {FrmPatro},
  ncafbPatrocinadores in '..\ncafbPatrocinadores.pas' {fbPatrocinadores: TFrmBasePai},
  ncaFrmPacote in '..\ncaFrmPacote.pas' {FrmPacote},
  ncClassesBase in '..\..\Comp\ncClassesBase.pas',
  ncaFrmZerarTempo in '..\ncaFrmZerarTempo.pas' {FrmZeraTempo},
  ncIDRecursos in '..\..\Comp\ncIDRecursos.pas',
  ncaFrmFundo in '..\ncaFrmFundo.pas' {FrmFundo},
  gifimage in 'C:\comp\gif\Sources\gifimage.pas',
  ncaColorConv in '..\ncaColorConv.pas',
  ncFrmChat in '..\..\Comp\ncFrmChat.pas' {FrmBaseChat},
  ncafbClientes in '..\ncafbClientes.pas' {fbClientes: TFrmBasePai},
  ncaFrmOpcaoRelCaixa in '..\ncaFrmOpcaoRelCaixa.pas' {FrmOpcaoRelCaixa},
  ncSessao in '..\..\Comp\ncSessao.pas',
  ncTarifador in '..\..\Comp\ncTarifador.pas',
  ncCompCliente in '..\..\Comp\ncCompCliente.pas',
  ncCredTempo in '..\..\Comp\ncCredTempo.pas',
  ncDMServ in '..\..\Comp\ncDMServ.pas' {DM: TDataModule},
  ncImpressao in '..\..\Comp\ncImpressao.pas',
  ncTran in '..\..\Comp\ncTran.pas',
  ncPassaportes in '..\..\Comp\ncPassaportes.pas',
  ncaFrmVendaProd in '..\ncaFrmVendaProd.pas' {FrmVendaProd},
  ncaFrmME in '..\ncaFrmME.pas' {FrmME},
  ncMovEst in '..\..\Comp\ncMovEst.pas',
  ncaFrmDebito in '..\ncaFrmDebito.pas' {FrmDebito},
  ncDebito in '..\..\Comp\ncDebito.pas',
  ncaFrmImp in '..\ncaFrmImp.pas' {FrmImp},
  ncDMCaixa in '..\..\Comp\ncDMCaixa.pas' {dmCaixa: TDataModule},
  ncaDMComp in '..\ncaDMComp.pas' {dmComp: TDataModule},
  ncafbFiltroWeb in '..\ncafbFiltroWeb.pas' {fbFiltroWeb: TFrmBasePai},
  ncListaEspera in '..\..\Comp\ncListaEspera.pas',
  ncaFrmEspera in '..\ncaFrmEspera.pas' {FrmEspera},
  ncaFrmProcessos in '..\ncaFrmProcessos.pas' {FrmProcessos},
  ncaFrmSite in '..\ncaFrmSite.pas' {FrmSite},
  uDMEmail in '..\..\..\Email\uDMEmail.pas' {dmEmail: TDataModule},
  ncafbTiposAcesso in '..\ncafbTiposAcesso.pas' {fbTiposAcesso: TFrmBasePai},
  ncaFrmCHorario in '..\ncaFrmCHorario.pas' {FrmCHorario},
  ncDebTempo in '..\..\Comp\ncDebTempo.pas',
  ncaFrmCorrigeDataCaixa in '..\ncaFrmCorrigeDataCaixa.pas' {FrmCorrigeDataCaixa},
  ncLancExtra in '..\..\Comp\ncLancExtra.pas',
  ncaFrmLancExtra in '..\ncaFrmLancExtra.pas' {FrmLancExtra},
  ncaFrmMaq in '..\ncaFrmMaq.pas' {FrmMaq},
  ncafbAvisos in '..\ncafbAvisos.pas' {fbAvisos: TFrmBasePai},
  ncaFrmAviso in '..\ncaFrmAviso.pas' {FrmAviso},
  udmLogmein in '..\..\Comp\udmLogmein.pas' {dmLogmein: TDataModule},
  ncaFrmImpPrePago in '..\ncaFrmImpPrePago.pas' {FrmImpPrePago},
  ncaLocalizaCli in '..\ncaLocalizaCli.pas' {FrmLocalizaCli},
  umsg in '..\..\..\Utils\umsg.pas',
  ncFrmCreditos in '..\..\Comp\ncFrmCreditos.pas' {FrmCreditos},
  uWinPopUp in 'C:\comp\winalert\uWinPopUp.pas' {FormWinPopUp},
  uWakeOnLan in '..\..\..\Utils\uWakeOnLan.pas',
  ncaFrmEmails in '..\ncaFrmEmails.pas' {FrmEmails},
  ncaFrmDebTempo in '..\ncaFrmDebTempo.pas' {FrmDebTempo},
  ncafbMovEst in '..\ncafbMovEst.pas' {fbMovEst: TFrmBasePai},
  ncaFrmObs in '..\ncaFrmObs.pas' {FrmObs},
  ncaBiometria in '..\ncaBiometria.pas' {FrmBio},
  GrFinger in '..\..\Comp\GrFinger.pas',
  GrFingerComp in '..\..\Comp\GrFingerComp.pas',
  ncDebug in '..\..\Comp\ncDebug.pas',
  ncMsgCom in '..\..\Comp\ncMsgCom.pas',
  ncVersionInfo in '..\..\Comp\ncVersionInfo.pas',
  ncNXServRemoto in '..\..\Comp\ncNXServRemoto.pas',
  ncNetMsg in '..\..\Comp\ncNetMsg.pas',
  ncaFrmErroConexao in '..\ncaFrmErroConexao.pas' {FrmErroConexao},
  ncErros in '..\..\Comp\ncErros.pas',
  ncFrmDownSup in '..\..\Comp\ncFrmDownSup.pas' {FrmDownSup},
  ncFrmSuporteRem in '..\..\Comp\ncFrmSuporteRem.pas' {FrmSuporte},
  rdDesktopView in '..\rdDesktopView.pas' {rdDesktopViewer},
  ncaFrmLiga in '..\ncaFrmLiga.pas' {FrmLiga},
  ncaFrmOperMaq in '..\ncaFrmOperMaq.pas' {FrmOperMaq},
  ncJob in '..\..\Comp\ncJob.pas',
  ncaFrmInfoMaq in '..\ncaFrmInfoMaq.pas' {FrmInfoMaq},
  ncaFrmMsgChat in '..\ncaFrmMsgChat.pas' {FrmMsgChat},
  ncafbTarifas in '..\ncafbTarifas.pas' {fbTarifas: TFrmBasePai},
  ncafbEst in '..\ncafbEst.pas' {fbEst: TFrmBasePai},
  ncafbTotCaixa in '..\ncafbTotCaixa.pas' {fbTotCaixa: TFrmBasePai},
  ncaFrmTarifa in '..\ncaFrmTarifa.pas' {FrmTarifa},
  ncafbTarifas2 in '..\ncafbTarifas2.pas' {fbTarifas2: TFrmBasePai},
  ncafbPass in '..\ncafbPass.pas' {fbPassaportes: TFrmBasePai},
  ncafbDiaHora in '..\ncafbDiaHora.pas' {fbTarDiaHora: TFrmBasePai},
  ncaFrmHorario in '..\ncaFrmHorario.pas' {FrmHorario},
  ncaFrmSemConta in '..\ncaFrmSemConta.pas' {FrmSemConta},
  ncaFrmAddMaq in '..\ncaFrmAddMaq.pas' {FrmAddMaq},
  VCLFixPack in '..\..\Comp\VCLFixPack.pas',
  ncaFrmTempoIniciar in '..\ncaFrmTempoIniciar.pas' {FrmTempoIniciar},
  ncaFrmIniciarSessao in '..\ncaFrmIniciarSessao.pas' {FrmIniciarSessao},
  ncaFrmSessao in '..\ncaFrmSessao.pas' {FrmSessao},
  ncaFrmTempo in '..\ncaFrmTempo.pas' {FrmTempo},
  ncaFrmAbrirCx in '..\ncaFrmAbrirCx.pas' {FrmAbrirCaixa},
  ncaFrmFechar in '..\ncaFrmFechar.pas' {FrmFecharCaixa},
  ncaFrmDataAtivo in '..\ncaFrmDataAtivo.pas' {FrmDataAtivo},
  ncaFrmCliPesq in '..\ncaFrmCliPesq.pas' {FrmCliPesq: TFrmBasePai},
  ncaFrmTipoAcesso in '..\ncaFrmTipoAcesso.pas' {FrmTipoAcesso},
  ncaFrmAss in '..\ncaFrmAss.pas' {FrmAss},
  uRSAss in '..\..\..\gs\uRSAss.pas',
  ncServAtualizaLic in '..\..\Comp\ncServAtualizaLic.pas' {dmAtualizaLic: TDataModule},
  ncafbPrevSessao in '..\ncafbPrevSessao.pas' {fbPrevSessao: TFrmBasePai},
  ncaFrmGetWebTabs in '..\ncaFrmGetWebTabs.pas' {FrmGetWebTabs},
  ncaPlusAPI in '..\ncaPlusAPI.pas' {FrmPlus},
  ncafbCXLetra in '..\ncafbCXLetra.pas' {fbCXLetra: TFrmBasePai},
  ncafbPesqFor in '..\ncafbPesqFor.pas' {fbPesqFor: TFrmBasePai},
  ncaFrmSenha in '..\ncaFrmSenha.pas' {FrmAlteraSenha},
  ncaFrmTempoDesligaMon in '..\ncaFrmTempoDesligaMon.pas' {FrmTempoDesligaMon},
  ncaFrmQtdMaq in '..\ncaFrmQtdMaq.pas' {FrmQtdMaq},
  ncaPlusParceiro in '..\ncaPlusParceiro.pas',
  md5 in '..\..\..\GS\md5.pas',
  ncaDMPlus in '..\ncaDMPlus.pas' {dmPlus: TDataModule},
  ncaFrmVendaPlus in '..\ncaFrmVendaPlus.pas' {FrmVendaPlus},
  ncaFrmFornecedor in '..\ncaFrmFornecedor.pas' {FrmFornecedor},
  ncaK in '..\..\Comp\ncaK.pas',
  ncCommPlusIndy in '..\..\Comp\ncCommPlusIndy.pas',
  ncDMcommPlus in '..\..\Comp\ncDMcommPlus.pas' {dmCommPlus: TDataModule},
  ncaFrmWebTab in '..\ncaFrmWebTab.pas' {FrmWebTab},
  ncaFrmErroNav in '..\ncaFrmErroNav.pas' {FrmErroNav},
  ncaFrmAguarde in '..\ncaFrmAguarde.pas' {FrmAguarde},
  ncaFrmCli in '..\ncaFrmCli.pas' {FrmCli},
  ncafbPesqCli in '..\ncafbPesqCli.pas' {fbPesqCli: TFrmBasePai},
  ncaFrmTotal in '..\ncaFrmTotal.pas' {FrmTotal},
  ncImgImp in '..\..\Comp\ncImgImp.pas' {dmImgImp: TDataModule},
  ncFirewall in '..\..\Comp\ncFirewall.pas',
  ncaFrmCriarConta2 in '..\ncaFrmCriarConta2.pas' {FrmCriarConta2},
  ncaFrmPanTopo in '..\ncaFrmPanTopo.pas' {FrmPanTopo},
  ncaFrmConn in '..\ncaFrmConn.pas' {FrmConn},
  uLicEXECryptor in '..\..\..\GS\uLicEXECryptor.pas',
  ncaFrmConfirmarReg in '..\ncaFrmConfirmarReg.pas' {FrmConfirmarReg},
  ncaFrmObrigado in '..\ncaFrmObrigado.pas' {FrmObrigado},
  uNR_chaveseg in '..\..\..\GS\uNR_chaveseg.pas',
  ncaFrmCorrigeEmail in '..\ncaFrmCorrigeEmail.pas' {FrmCorrigeEmail},
  ncFrmPrintReview in '..\..\PrintReview\ncFrmPrintReview.pas' {FrmPrintReview},
  uFrmComSombra in '..\..\..\Utils\uFrmComSombra.pas' {FrmComSombra},
  ncPRTransfer in '..\..\PrintReview\ncPRTransfer.pas',
  ncaFrmPTProgress in '..\..\Guard\ncaFrmPTProgress.pas' {FrmPTProgress},
  ncPrintDoc in '..\..\Comp\ncPrintDoc.pas',
  ncPRConsts in '..\..\printreview\ncPRConsts.pas',
  ncShellStart in '..\..\Comp\ncShellStart.pas',
  ncPRBaseClasses in '..\..\PrintReview\ncPRBaseClasses.pas',
  ncPRThumbsScrollBox in '..\..\PrintReview\ncPRThumbsScrollBox.pas',
  ncThreadedDownload in '..\..\Comp\ncThreadedDownload.pas',
  ncPRFrmPrintTipo in '..\..\PrintReview\ncPRFrmPrintTipo.pas' {FrmPrintTipo},
  ncPRFrmEtapas in '..\..\PrintReview\ncPRFrmEtapas.pas' {FrmPREtapas},
  ncTipoImp in '..\..\Comp\ncTipoImp.pas',
  ncBaseWebApi in '..\..\Comp\ncBaseWebApi.pas',
  ncWBFrameExecScript in '..\..\Comp\ncWBFrameExecScript.pas',
  ncaBaseWebApi in '..\ncaBaseWebApi.pas',
  ncFrmWebPopup in '..\..\Comp\ncFrmWebPopup.pas' {FrmWebPopup},
  ncaFrmWebPopup in '..\ncaFrmWebPopup.pas' {AdminFrmWebPopup},
  ncVersoes in '..\..\comp\ncVersoes.pas',
  ncaFrmPMNaoPausar in '..\ncaFrmPMNaoPausar.pas' {FrmPMNaoPausar},
  ncaFrmPMConfigConfirma in '..\ncaFrmPMConfigConfirma.pas' {FrmConfigConfirma},
  ncaFrmImpNexCafe in '..\ncaFrmImpNexCafe.pas' {FrmImpNexCafe},
  ncKiteApi in '..\..\Comp\ncKiteApi.pas',
  ncafbVendas2 in '..\ncafbVendas2.pas' {fbVendas2: TFrmBasePai},
  ncaFrmConfigRec in '..\ncaFrmConfigRec.pas' {FrmConfigRecibo},
  ncafbCHATHist in '..\ncafbCHATHist.pas' {fbChatHist: TFrmBasePai},
  ncaFrmCorrigeData in '..\ncaFrmCorrigeData.pas' {FrmCorrigeData},
  ncaFrmSombra in '..\ncaFrmSombra.pas' {FrmSombra2},
  ncaFrmConta in '..\ncaFrmConta.pas' {FrmInfConta},
  ncaFrmWebCam in '..\ncaFrmWebCam.pas' {FrmWebCam},
  ncafbPrintMon in '..\ncafbPrintMon.pas' {fbPrintMon: TFrmBasePai},
  ncaFrmConfigEmailCaixa in '..\ncaFrmConfigEmailCaixa.pas' {FrmConfigEmailCaixa},
  ncaWebcam in '..\ncaWebcam.pas',
  ncafbFornecedores in '..\ncafbFornecedores.pas' {fbFornecedores: TFrmBasePai},
  ncaFrmCadCli in '..\ncaFrmCadCli.pas' {FrmCadCli},
  ncaFrmConfigAutoCad in '..\ncaFrmConfigAutoCad.pas' {FrmConfigAutoCad},
  ncaFrmLimiteDebPadrao in '..\ncaFrmLimiteDebPadrao.pas' {FrmLimiteDeb},
  ncaFrmProduto in '..\ncaFrmProduto.pas' {FrmProduto},
  ncaFrmQuickCadProduto in '..\ncaFrmQuickCadProduto.pas' {FrmQuickCadProduto},
  ncafbRevisarProduto in '..\ncafbRevisarProduto.pas' {fbRevisarProduto: TFrmBasePai},
  ncaFrmConfigLogin in '..\ncaFrmConfigLogin.pas' {FrmConfigLogin},
  ncaConnMgr in '..\ncaConnMgr.pas',
  ncaFrmEnviaSenha in '..\ncaFrmEnviaSenha.pas' {FrmEnviaSenha},
  ncaFrmBaseOpcao in '..\ncaFrmBaseOpcao.pas' {FrmBaseOpcao},
  ncaFrmConfigCaixaFechamento in '..\ncaFrmConfigCaixaFechamento.pas' {FrmConfigCaixaFechamento},
  ncaFrmBaseOpcaoImgTxt in '..\ncaFrmBaseOpcaoImgTxt.pas' {FrmBaseOpcaoImgTxt},
  ncaFrmOpcoes in '..\ncaFrmOpcoes.pas' {FrmOpcoes},
  ncaFrmConfigCaixaAbertura in '..\ncaFrmConfigCaixaAbertura.pas' {FrmConfigCaixaAbertura},
  ncaFrmProduto_Estoque in '..\ncaFrmProduto_Estoque.pas' {FrmProd_Estoque},
  ncaFrmProduto_PrecoAuto in '..\ncaFrmProduto_PrecoAuto.pas' {FrmProd_PrecoAuto},
  ncaFrmConfigPrecoAuto in '..\ncaFrmConfigPrecoAuto.pas',
  ncaFrmSaibaMaisClonar in '..\ncaFrmSaibaMaisClonar.pas' {FrmSaibaMaisClonar},
  ncaFrmChecarCodProdutoDuplicado in '..\ncaFrmChecarCodProdutoDuplicado.pas' {FrmChecarCodProdutoDuplicado},
  ncaFrmConfigCodProdutoDuplicado in '..\ncaFrmConfigCodProdutoDuplicado.pas',
  ncaFrmBaseOpcaoImgTxtCheckBox in '..\ncaFrmBaseOpcaoImgTxtCheckBox.pas',
  ncaFrmConfigQuickCad in '..\ncaFrmConfigQuickCad.pas',
  ncaAlertaAutocad in '..\ncaAlertaAutocad.pas',
  ncaAlertaClonarProduto in '..\ncaAlertaClonarProduto.pas',
  ncaPanBaseAlertaTopo in '..\ncaPanBaseAlertaTopo.pas' {panAlertaTopo: TFrame},
  ncaFrmBasicTextEdit in '..\ncaFrmBasicTextEdit.pas' {FrmBasicTextEdit},
  ncaPanVendaProdBase in '..\ncaPanVendaProdBase.pas' {FrmPanVendaProdBase},
  ncaPanItensVendaBase in '..\ncaPanItensVendaBase.pas' {panItensVendaBase},
  ncaPanItensVendaGrid in '..\ncaPanItensVendaGrid.pas' {panItensVendaGrid},
  ncaFrmConfigChoiceME in '..\ncaFrmConfigChoiceME.pas' {FrmConfigChoiceME},
  ncaFrmConfigVendaProdSemSaldo in '..\ncaFrmConfigVendaProdSemSaldo.pas';

{$R *.res}
{$R uac.res}

begin
  Application.Initialize;
  gGuardSide := False;
  NomeArqDebug := 'DebugNexAdmin.txt';
  
  Application.Title := 'NexAdmin';
  
  Application.CreateForm(TDados, Dados);
  Application.CreateForm(TdmImagens, dmImagens);
  Application.CreateForm(TdmImgImp, dmImgImp);
  Application.CreateForm(TFrmPri, FrmPri);
  Application.CreateForm(TFrmConfigChoiceME, FrmConfigChoiceME);
  gWndParent := FrmPri.Handle;
  Application.CreateForm(TFrmPrintTipo, FrmPrintTipo);
  Application.CreateForm(TFrmPREtapas, FrmPREtapas);
  Application.CreateForm(TFrmPMNaoPausar, FrmPMNaoPausar);
  Application.CreateForm(TFrmConfigConfirma, FrmConfigConfirma);
  Application.CreateForm(TFrmCorrigeData, FrmCorrigeData);
  Application.CreateForm(TFrmLocalizaCli, FrmLocalizaCli);
  Application.CreateForm(TFormWinPopUp, FormWinPopUp);
  Application.CreateForm(TFrmDownSup, FrmDownSup);
  Application.CreateForm(TFrmSuporte, FrmSuporte);
  Application.CreateForm(TdmAtualizaLic, dmAtualizaLic);
  Application.CreateForm(TFrmPanTopo, FrmPanTopo);
  Application.CreateForm(TFrmPrintReview, FrmPrintReview);
  Application.CreateForm(TFrmComSombra, FrmComSombra);
  Application.CreateForm(TFrmPTProgress, FrmPTProgress);
  Application.Run;
  Dados.Free;
  NomeArqDebug := '';
end.
