program NexAdmin_Loja;


uses
  LMDPngImage,
  ncaCurrFormat in 'ncaCurrFormat.pas',
  Forms,
  nxllZipCompressor,
  nxllRLECompressor,    
  System.SysUtils,
  cxFormats,
  ncaDM in 'ncaDM.pas' {Dados: TDataModule},
  ufmImagens in 'ufmImagens.pas' {dmImagens: TDataModule},
  ufmFormBase in '..\..\FormMgr\ufmFormBase.pas' {FrmBase: TFrmBasePai},
  ncaFrmLogin in 'ncaFrmLogin.pas' {FrmLogin},
  ncafbTran in 'ncafbTran.pas' {fbTran: TFrmBasePai},
  ncaFrmTipos in 'ncaFrmTipos.pas' {FrmTipos},
  ncaFrmCadTranspEnt in 'ncaFrmCadTranspEnt.pas' {FrmCadTranspEnt},
  ncafbProdutos in 'ncafbProdutos.pas' {fbProdutos: TFrmBasePai},
  ncafgExtratoFid in 'ncafgExtratoFid.pas' {fbExtratoFid: TFrmBasePai},
  ncaFrmUsuario in 'ncaFrmUsuario.pas' {FrmUsuario},
  ncaFrmSenhaWiz in 'ncaFrmSenhaWiz.pas' {FrmSenhaWiz},
  ncafbCaixa in 'ncafbCaixa.pas' {fbCaixa: TFrmBasePai},
  ncafbCaixasA in 'ncafbCaixasA.pas' {fbCaixasA: TFrmBasePai},
  ncaFrmCaixa in 'ncaFrmCaixa.pas' {FrmCaixa},
  ncafbUsuarios in 'ncafbUsuarios.pas' {fbUsuarios: TFrmBasePai},
  ncaFrmAjustaFid in 'ncaFrmAjustaFid.pas' {FrmAjustaFid},
  ncaFrmContato in 'ncaFrmContato.pas' {FrmContato},
  ncaFrmHistVer in 'ncaFrmHistVer.pas' {FrmRTF},
  ncClassesBase in '..\Comp\ncClassesBase.pas',
  ncIDRecursos in '..\Comp\ncIDRecursos.pas',
  ncaColorConv in 'ncaColorConv.pas',
  ncafbClientes in 'ncafbClientes.pas' {fbClientes: TFrmBasePai},
  ncaFrmOpcaoRelCaixa in 'ncaFrmOpcaoRelCaixa.pas' {FrmOpcaoRelCaixa},
  ncCompCliente in '..\Comp\ncCompCliente.pas',
  ncDMServ in '..\Comp\ncDMServ.pas' {DM: TDataModule},
  ncTran in '..\Comp\ncTran.pas',
  ncMovEst in '..\Comp\ncMovEst.pas',
  ncDebito in '..\Comp\ncDebito.pas',
  ncDMCaixa in '..\comp\ncDMCaixa.pas' {dmCaixa: TDataModule},
  ncaDMComp in 'ncaDMComp.pas' {dmComp: TDataModule},
  ncaFrmSite in 'ncaFrmSite.pas' {FrmSite},
  ncSalvaCredito in '..\comp\ncSalvaCredito.pas',
  ncaFrmCorrigeDataCaixa in 'ncaFrmCorrigeDataCaixa.pas' {FrmCorrigeDataCaixa},
  ncLancExtra in '..\Comp\ncLancExtra.pas',
  ncaFrmLancExtra in 'ncaFrmLancExtra.pas' {FrmLancExtra},
  ncafbAvisos in 'ncafbAvisos.pas' {fbAvisos: TFrmBasePai},
  ncaLocalizaCli in 'ncaLocalizaCli.pas' {FrmLocalizaCli},
  umsg in '..\..\Utils\umsg.pas',
  ncaFrmEmails in 'ncaFrmEmails.pas' {FrmEmails},
  ncaFrmCorrigeCredito in 'ncaFrmCorrigeCredito.pas' {FrmCorrigeCredito},
  ncafbMEPend in 'ncafbMEPend.pas' {fbMEPend: TFrmBasePai},
  ncaFrmJust in 'ncaFrmJust.pas' {FrmJust},
  ncDebug in '..\Comp\ncDebug.pas',
  ncMsgCom in '..\Comp\ncMsgCom.pas',
  ncVersionInfo in '..\Comp\ncVersionInfo.pas',
  ncNXServRemoto in '..\Comp\ncNXServRemoto.pas',
  ncNetMsg in '..\Comp\ncNetMsg.pas',
  ncaFrmErroConexao in 'ncaFrmErroConexao.pas' {FrmErroConexao},
  ncErros in '..\Comp\ncErros.pas',
  ncFrmDownSup in '..\Comp\ncFrmDownSup.pas' {FrmDownSup},
  ncFrmSuporteRem in '..\Comp\ncFrmSuporteRem.pas' {FrmSuporte},
  ncaFrmLiga in 'ncaFrmLiga.pas' {FrmLiga},
  ncaFrmInfoMaq in 'ncaFrmInfoMaq.pas' {FrmInfoMaq},
  ncafbEst in 'ncafbEst.pas' {fbEst: TFrmBasePai},
  ncafbTotCaixa in 'ncafbTotCaixa.pas' {fbTotCaixa: TFrmBasePai},
  ncaFrmAbrirCx in 'ncaFrmAbrirCx.pas' {FrmAbrirCaixa},
  ncaFrmFechar in 'ncaFrmFechar.pas' {FrmFecharCaixa},
  ncaFrmDataAtivo in 'ncaFrmDataAtivo.pas' {FrmDataAtivo},
  uRSAss in '..\..\gs\uRSAss.pas',
  ncaFrmGetWebTabs in 'ncaFrmGetWebTabs.pas' {FrmGetWebTabs},
  ncafbCXLetra in 'ncafbCXLetra.pas' {fbCXLetra: TFrmBasePai},
  ncafbPesqFor in 'ncafbPesqFor.pas' {fbPesqFor: TFrmBasePai},
  ncaFrmSenha in 'ncaFrmSenha.pas' {FrmAlteraSenha},
  ncaFrmQtdMaq in 'ncaFrmQtdMaq.pas' {FrmQtdMaq},
  ncaFrmFornecedor in 'ncaFrmFornecedor.pas' {FrmFornecedor},
  ncaK in '..\Comp\ncaK.pas',
  ncaFrmWebTab in 'ncaFrmWebTab.pas' {FrmWebTab},
  ncaFrmErroNav in 'ncaFrmErroNav.pas' {FrmErroNav},
  ncaFrmAguarde in 'ncaFrmAguarde.pas' {FrmAguarde},
  ncFirewall in '..\Comp\ncFirewall.pas',
  ncaFrmCriarConta2 in 'ncaFrmCriarConta2.pas' {FrmCriarConta2},
  ncaFrmPanTopo in 'ncaFrmPanTopo.pas' {FrmPanTopo},
  ncaFrmConn in 'ncaFrmConn.pas' {FrmConn},
  uLicEXECryptor in '..\..\GS\uLicEXECryptor.pas',
  ncaFrmConfirmarReg in 'ncaFrmConfirmarReg.pas' {FrmConfirmarReg},
  ncaFrmObrigado in 'ncaFrmObrigado.pas' {FrmObrigado},
  uNR_chaveseg in '..\..\GS\uNR_chaveseg.pas',
  ncaFrmCorrigeEmail in 'ncaFrmCorrigeEmail.pas' {FrmCorrigeEmail},
  ncShellStart in '..\Comp\ncShellStart.pas',
  ncThreadedDownload in '..\Comp\ncThreadedDownload.pas',
  ncBaseWebApi in '..\Comp\ncBaseWebApi.pas',
  ncaBaseWebApi in 'ncaBaseWebApi.pas',
  ncFrmWebPopup in '..\Comp\ncFrmWebPopup.pas' {FrmWebPopup},
  ncaFrmWebPopup in 'ncaFrmWebPopup.pas' {AdminFrmWebPopup},
  ncVersoes in '..\comp\ncVersoes.pas',
  ncafbTranEst in 'ncafbTranEst.pas' {fbTranEst: TFrmBasePai},
  ncaFrmCorrigeData in 'ncaFrmCorrigeData.pas' {FrmCorrigeData},
  ncaFrmSombra in 'ncaFrmSombra.pas' {FrmSombra2},
  ncaFrmConta in 'ncaFrmConta.pas' {FrmInfConta},
  ncaFrmWebCam2 in 'ncaFrmWebCam2.pas' {FrmWebCam2},
  ncaFrmConfigEmailCaixa in 'ncaFrmConfigEmailCaixa.pas' {FrmConfigEmailCaixa},
  ncaWebcam in 'ncaWebcam.pas',
  ncafbFornecedores in 'ncafbFornecedores.pas' {fbFornecedores: TFrmBasePai},
  ncaFrmCadCli in 'ncaFrmCadCli.pas' {FrmCadCli},
  ncaFrmConfigConfirmaDeb in 'ncaFrmConfigConfirmaDeb.pas' {FrmConfigConfirmaDeb},
  ncaFrmLimiteDebPadrao in 'ncaFrmLimiteDebPadrao.pas' {FrmLimiteDeb},
  ncafbRevisarProduto in 'ncafbRevisarProduto.pas' {fbRevisarProduto: TFrmBasePai},
  ncaFrmConfigQuickCad in 'ncaFrmConfigQuickCad.pas' {FrmConfigQuickCad},
  ncaFrmSaibaMaisClonar in 'ncaFrmSaibaMaisClonar.pas' {FrmSaibaMaisClonar},
  ncaFrmChecarCodProdutoDuplicado in 'ncaFrmChecarCodProdutoDuplicado.pas' {FrmChecarCodProdutoDuplicado},
  ncaFrmConfigCodProdutoDuplicado in 'ncaFrmConfigCodProdutoDuplicado.pas' {FrmConfigCodProdutoDuplicado},
  ncaFrmEscolhaProdDup in 'ncaFrmEscolhaProdDup.pas' {FrmEscolhaProdDup},
  ncaFrmConfigChoiceME in 'ncaFrmConfigChoiceME.pas' {FrmConfigChoiceME},
  ncFrmCriarConta in '..\Comp\ncFrmCriarConta.pas' {FrmCriarConta},
  ncaFrmConfigCaixaFechamento in 'ncaFrmConfigCaixaFechamento.pas' {FrmConfigCaixaFechamento},
  ncaFrmConfigCaixaAbertura in 'ncaFrmConfigCaixaAbertura.pas' {FrmConfigCaixaAbertura},
  ncaFrmOpcoes in 'ncaFrmOpcoes.pas' {FrmOpcoes},
  ncaFrmBaseOpcao in 'ncaFrmBaseOpcao.pas' {FrmBaseOpcao},
  ncaFrmBaseOpcaoImgTxt in 'ncaFrmBaseOpcaoImgTxt.pas' {FrmBaseOpcaoImgTxt},
  ncaFrmBaseOpcaoImgTxtCheckBox in 'ncaFrmBaseOpcaoImgTxtCheckBox.pas' {FrmBaseOpcaoImgTxtCheckBox},
  ncaFrmConfigVendaProdSemSaldo in 'ncaFrmConfigVendaProdSemSaldo.pas' {FrmConfigVendaProdSemSaldo},
  ncaFrmConfigDanfe_SAT in 'ncaFrmConfigDanfe_SAT.pas' {FrmConfigDanfe_SAT},
  Countries in '..\..\Utils\Countries.pas',
  ncafbVendasTab in 'ncafbVendasTab.pas' {fbVendasTab: TFrmBasePai},
  ncaFrmOrcamento in 'ncaFrmOrcamento.pas' {FrmOrcamento},
  ncaPanVendaProdBase in 'ncaPanVendaProdBase.pas' {FrmPanVendaProdBase},
  ncaPanVendaProd2 in 'ncaPanVendaProd2.pas' {FrmPanVendaProd2},
  ncaPanItensVendaBase in 'ncaPanItensVendaBase.pas' {panItensVendaBase},
  ncaPanItensVendaGrid in 'ncaPanItensVendaGrid.pas' {panItensVendaGrid},
  ncaFrmProdPesq in 'ncaFrmProdPesq.pas' {FrmProdPesq: TFrmBasePai},
  uNexTransResourceStrings_PT in '..\..\FormMgr\translator\uNexTransResourceStrings_PT.pas',
  ncaFrmPesqFor in 'ncaFrmPesqFor.pas' {FrmPesqFor: TFrmBasePai},
  uFrmPanFaixas in '..\..\Utils\uFrmPanFaixas.pas' {FrmFaixas},
  uFrmPanFaixa in '..\..\Utils\uFrmPanFaixa.pas' {FrmPanFaixa},
  ncafbPesqCli in 'ncafbPesqCli.pas' {fbPesqCli: TFrmBasePai},
  ncEspecie in '..\Comp\ncEspecie.pas',
  ncaPanBaseAlertaTopo in 'ncaPanBaseAlertaTopo.pas' {panAlertaTopo: TFrame},
  ncaAlertaClonarProduto in 'ncaAlertaClonarProduto.pas' {panAlertaClonarProduto: TFrame},
  ncaAlertaAutocad in 'ncaAlertaAutocad.pas' {panAlertaAutocad: TFrame},
  ncaFrmProduto_PrecoAuto in 'ncaFrmProduto_PrecoAuto.pas' {FrmProd_PrecoAuto},
  ncaFrmConfigPrecoAuto in 'ncaFrmConfigPrecoAuto.pas' {FrmConfigPrecoAuto},
  ncaFrmProduto_Estoque in 'ncaFrmProduto_Estoque.pas' {FrmProd_Estoque},
  ncaFrmNCM in 'ncaFrmNCM.pas' {FrmNCM},
  ncaFrmConfigRec_Serial in 'ncaFrmConfigRec_Serial.pas' {FrmConfigRec_Serial},
  ncaFrmConfigLogin in 'ncaFrmConfigLogin.pas' {FrmConfigLogin},
  ncaConnMgr in 'ncaConnMgr.pas',
  ncaFrmEnviaSenha in 'ncaFrmEnviaSenha.pas' {FrmEnviaSenha},
  ncaFrmSemEstoque in 'ncaFrmSemEstoque.pas' {FrmSemEstoque},
  uParentedPanel in '..\..\FormMgr\uParentedPanel.pas',
  ncaFrmEditFunc in 'ncaFrmEditFunc.pas' {FrmEditFunc},
  ncaFrmPagEspecie in 'ncaFrmPagEspecie.pas' {FrmPagEspecie},
  ncaFrmFuncPesq in 'ncaFrmFuncPesq.pas' {FrmFuncPesq},
  ncaFrmTotal in 'ncaFrmTotal.pas' {FrmTotal},
  ncaFrmTipoRec in 'ncaFrmTipoRec.pas' {FrmTipoRec},
  ncaDMImgEsp in 'ncaDMImgEsp.pas' {dmImgEsp: TDataModule},
  ncaFrmConfigEspecies in 'ncaFrmConfigEspecies.pas' {FrmConfigEspecies},
  ncaConfigEspecie in 'ncaConfigEspecie.pas' {FrmConfigEspecie},
  ncafbPagEsp in 'ncafbPagEsp.pas' {fbPagEsp: TFrmBasePai},
  ncaFramePagamento in 'ncaFramePagamento.pas' {FramePagamento: TFrame},
  ncaFrmEditDesc in 'ncaFrmEditDesc.pas' {FrmEditDesc},
  ncaFrmEditObs in 'ncaFrmEditObs.pas' {FrmEditObs},
  ncaFrmEditContato in 'ncaFrmEditContato.pas' {FrmEditContato},
  ncaFrmPesqCFOP in 'ncaFrmPesqCFOP.pas' {FrmPesqCFOP},
  ncaFrmEditContatoPeq in 'ncaFrmEditContatoPeq.pas' {FrmEditContatoPeq},
  ncaFrmEditContatoValidar in 'ncaFrmEditContatoValidar.pas' {FrmEditContatoValidar},
  ncDebCredValidator in '..\comp\ncDebCredValidator.pas',
  ncaFrmConfigAutoCad in 'ncaFrmConfigAutoCad.pas' {FrmConfigAutoCad},
  ncaWebBanner in 'ncaWebBanner.pas' {FrmWebBanner},
  ncaWebBotao in 'ncaWebBotao.pas',
  ncaFrmDebito in 'ncaFrmDebito.pas' {FrmDebito},
  ncaFrmConfigFid in 'ncaFrmConfigFid.pas' {FrmConfigFid},
  ncaFrmProdSemFid in 'ncaFrmProdSemFid.pas' {FrmProdSemFid},
  ncaFrmConfigComissao in 'ncaFrmConfigComissao.pas' {FrmConfigComissao},
  ncaFrmConfigCodBarBal in 'ncaFrmConfigCodBarBal.pas' {FrmConfigCodBarBal},
  ncaFrmConfigTelaVendas in 'ncaFrmConfigTelaVendas.pas' {FrmConfigTelaVendas},
  ncSyncLic in '..\comp\ncSyncLic.pas',
  ncListaID in '..\comp\ncListaID.pas',
  Automation in '..\comp\Automation.pas',
  ncCheckWin64 in '..\comp\ncCheckWin64.pas',
  ncMyImage in '..\comp\ncMyImage.pas',
  ncHash in '..\comp\ncHash.pas',
  ncCommonProc in '..\comp\ncCommonProc.pas',
  ncDeleteFiles in '..\comp\ncDeleteFiles.pas',
  ncDirUtils in '..\comp\ncDirUtils.pas',
  ncaConfigRecibo in 'ncaConfigRecibo.pas',
  ncaFrmConfig_CodBar_Precisao in 'ncaFrmConfig_CodBar_Precisao.pas' {FrmConfig_CodBar_Precisao},
  frxExportTXT in 'C:\comp\fr5\Source\ExportPack\frxExportTXT.pas' {frxTXTExportDialog},
  ncaFrmAposOrc in 'ncaFrmAposOrc.pas' {FrmAposOrc},
  ncGuidUtils in '..\comp\ncGuidUtils.pas',
  ncaFrmConfigPosVenda in 'ncaFrmConfigPosVenda.pas' {FrmConfigPosVenda},
  ncaFrmImprimeEtq in 'ncaFrmImprimeEtq.pas' {FrmImprimeEtq},
  ncaFrmNovaEtiqueta in 'ncaFrmNovaEtiqueta.pas' {FrmNovaEtiqueta},
  ncaFrmQuantEtq in 'ncaFrmQuantEtq.pas' {FrmQuantEtq},
  ncaFrmRenameEtq in 'ncaFrmRenameEtq.pas' {FrmRenomear},
  dxBar in 'C:\comp\devex\ExpressBars\Sources\dxBar.pas',
  ncaAlertaRecuperarVenda in 'ncaAlertaRecuperarVenda.pas' {panAlertaRecuperarVenda: TFrame},
  ncaFrmPopupAss in 'ncaFrmPopupAss.pas' {FrmPopupAss},
  ncaAlertaTrial in 'ncaAlertaTrial.pas' {panAlertaTrial: TFrame},
  ncaFrmOnTrial in 'ncaFrmOnTrial.pas' {FrmOnTrial},
  ncaFrmRecursoPremium in 'ncaFrmRecursoPremium.pas' {FrmRecursoPremium},
  ncafbOrcamento in 'ncafbOrcamento.pas' {fbOrcamento: TFrmBasePai},
  ncaFrmME2 in 'ncaFrmME2.pas' {FrmME2},
  ncaFrmTotalOrcamento in 'ncaFrmTotalOrcamento.pas' {FrmTotalOrcamento},
  ncaFrmTotal3 in 'ncaFrmTotal3.pas' {FrmTotal3},
  ncaFrmEditValidade in 'ncaFrmEditValidade.pas' {FrmEditValidade},
  ncaFrmEditContatoOrc in 'ncaFrmEditContatoOrc.pas' {FrmEditContatoOrc},
  ncaDMorc in 'ncaDMorc.pas' {dmOrc: TDataModule},
  ncaFrmAposVenda in 'ncaFrmAposVenda.pas' {FrmAposVenda},
  ncaFrmSubject in 'ncaFrmSubject.pas' {FrmSubject},
  ncaFrmFromEmail in 'ncaFrmFromEmail.pas' {FrmFromEmail},
  ncaFrmConfigDocOrc in 'ncaFrmConfigDocOrc.pas' {FrmConfigDocOrc},
  ncaFrmSendEmailOrc in 'ncaFrmSendEmailOrc.pas' {FrmSendEmail},
  kwicDescriptor in '..\..\kwic\kwicDescriptor.pas',
  kwicEngine in '..\..\kwic\kwicEngine.pas',
  ncHttp in '..\comp\ncHttp.pas',
  md5 in 'C:\comp\varios\md5.pas',
  uGetSerial in '..\..\gs\uGetSerial.pas',
  ncaFrmPri in 'ncaFrmPri.pas' {FrmPri},
  ncCaixas in '..\comp\ncCaixas.pas',
  ncaFrmDoc in 'ncaFrmDoc.pas' {FrmDoc},
  ncaDocMgr in 'ncaDocMgr.pas' {FrmDocMgr},
  ncaGM_FrmParam in 'ncaGM_FrmParam.pas' {FrmGMParam},
  ncaTermID in 'ncaTermID.pas',
  ncaDocEdit in 'ncaDocEdit.pas',
  ncDMSyncCest in '..\comp\ncDMSyncCest.pas' {dmCestUpdate: TDataModule},
  nexUrls in '..\..\nxUrl\nexUrls.pas',
  ncKiteApi in '..\..\kapi\ncKiteApi.pas',
  ncaFrmFormatoDemDeb in 'ncaFrmFormatoDemDeb.pas' {FrmFormatoDemDeb},
  ncaFrmDevolucao in 'ncaFrmDevolucao.pas' {FrmDev},
  ncaFrmCliPesq2 in 'ncaFrmCliPesq2.pas' {FrmCliPesq2},
  ncServAtualizaLic_Indy in '..\comp\ncServAtualizaLic_Indy.pas' {dmAtualizaLic: TDataModule},
  ncaFrmConfig_ExigirVendedor in 'ncaFrmConfig_ExigirVendedor.pas' {FrmConfig_ExigirVendedor},
  ncaFrmQtdDev in 'ncaFrmQtdDev.pas' {FrmQtdDev},
  ncafbMovEst in 'ncafbMovEst.pas' {fbMovEst: TFrmBasePai},
  ncaPlusAPI in 'ncaPlusAPI.pas' {FrmPlus},
  ncIPAddr in '..\comp\ncIPAddr.pas',
  ncaFrmProduto in 'ncaFrmProduto.pas' {FrmProduto},
  ncaFrmProdPesq2 in 'ncaFrmProdPesq2.pas' {FrmProdPesq2},
  ncaFrmBasicTextEdit in 'ncaFrmBasicTextEdit.pas' {FrmBasicTextEdit},
  uProxCampo in '..\Utils\uProxCampo.pas',
  ncaFrmNCMEx in 'ncaFrmNCMEx.pas' {FrmNCMEx},
  ncaFrmConfig_Cupom in 'ncaFrmConfig_Cupom.pas' {FrmConfig_Cupom},
  ncaFrmMunBr in 'ncaFrmMunBr.pas' {FrmMunPesq},
  ncaFrmBaseCadastro in 'ncaFrmBaseCadastro.pas' {FrmBaseCadastro},
  ncaFrmBaseCadastroMT in 'ncaFrmBaseCadastroMT.pas' {FrmBaseCadastroMT},
  ncaFrmTax in 'ncaFrmTax.pas' {FrmTax},
  ncDMdanfe_SAT in '..\comp\ncDMdanfe_SAT.pas' {dmDanfe_SAT: TDataModule},
  ncafbCupom in 'ncafbCupom.pas' {fbCupom: TFrmBasePai},
  ncaFrmTaxPesq in 'ncaFrmTaxPesq.pas' {FrmTaxPesq},
  ncaFrmConfigRec in 'ncaFrmConfigRec.pas' {FrmConfigRec_Venda},
  ncaFrmCESTPesq in 'ncaFrmCESTPesq.pas' {FrmCESTPesq},
  ncaFrmCCEOk in 'ncaFrmCCEOk.pas' {FrmCCEOk},
  ncaAlertaNFCe in 'ncaAlertaNFCe.pas' {panAlertaTopo2: TFrame},
  ncaEditEmail in 'ncaEditEmail.pas' {FrmEditEmail},
  ncaFrmCCe in 'ncaFrmCCe.pas' {FrmCCe},
  ncaFrmRej in 'ncaFrmRej.pas' {FrmRej},
  ncaFrmCCERej in 'ncaFrmCCERej.pas' {FrmCCERej},
  ncaFrmNCMEdit in 'ncaFrmNCMEdit.pas' {FrmNCMEdit},
  ncaFrmRecursoPRO in 'ncaFrmRecursoPRO.pas' {FrmRecursoPro},
  ncaFrmDadosNFCe in 'ncaFrmDadosNFCe.pas' {FrmDadosNFCe},
  ncaFrmUpgradePremium in 'ncaFrmUpgradePremium.pas' {FrmUpgradePremium},
  ncaFrmReativarNF in 'ncaFrmReativarNF.pas' {FrmReativarNF},
  ncaFrmNFeDepend in 'ncaFrmNFeDepend.pas' {FrmNFeDepend},
  ncaProgressoDepend in 'ncaProgressoDepend.pas' {panProgressoDepend: TFrame},
  ncaFrmNFCeImpedirDeslig in 'ncaFrmNFCeImpedirDeslig.pas' {FrmNFCeImpedirDeslig},
  ncaFrmMigrarPremium in 'ncaFrmMigrarPremium.pas' {FrmMigrarPremium},
  ncaFrmRemoverNF in 'ncaFrmRemoverNF.pas' {FrmRemoverNF},
  ncaFrmXmls in 'ncaFrmXmls.pas' {FrmXMLs},
  ncaFrmNFeModoHomo in 'ncaFrmNFeModoHomo.pas' {FrmNFeModoHomo},
  ncaFrmNFeMigrarProd in 'ncaFrmNFeMigrarProd.pas' {FrmNFeMigrarProd},
  ncaFrmAlertaPIN in 'ncaFrmAlertaPIN.pas' {FrmAlertaPIN},
  ncaFrmNFCeCancelarHomo in 'ncaFrmNFCeCancelarHomo.pas' {FrmNFCeCancelarHomo},
  ncaFrmOpcoesRelNFVendas in 'ncaFrmOpcoesRelNFVendas.pas' {FrmOpRelNFVendas},
  ncaDMDemonstrativoDeb in 'ncaDMDemonstrativoDeb.pas' {dmDemonstrativoDeb: TDataModule},
  ncaFrmConfig_Orcamento in 'ncaFrmConfig_Orcamento.pas' {FrmConfig_Orcamento},
  ncaFrmPanFor in 'ncaFrmPanFor.pas' {FrmPanFor},
  ncaFrmListaFornecedores in 'ncaFrmListaFornecedores.pas' {FrmListaFornecedores},
  ncaFrmLeXML in 'ncaFrmLeXML.pas' {FrmLeXML},
  ncaFrmTrocoMax in 'ncaFrmTrocoMax.pas' {FrmTrocoMax},
  htmlCodec in '..\..\utils\htmlCodec.pas',
  ncDMdanfe_nfe in '..\comp\ncDMdanfe_nfe.pas' {dmDanfe_nfe: TDataModule},
  ncaFrmConfigDanfe_NFe in 'ncaFrmConfigDanfe_NFe.pas' {FrmConfigDanfe_NFe},
  ncaFrmSuporteDB in 'ncaFrmSuporteDB.pas' {FrmSuporteDB},
  ncaFrmDBPanel in 'ncaFrmDBPanel.pas' {FrmDBPanel},
  ncaSenhaToken in 'ncaSenhaToken.pas',
  Vcl.OleCtrls in 'c:\program files (x86)\embarcadero\studio\17.0\SOURCE\VCL\Vcl.OleCtrls.pas',
  uMyBrowser in '..\..\MyBrowser\uMyBrowser.pas',
  ncaFrmPeriodo in 'ncaFrmPeriodo.pas' {FrmPeriodo},
  ncaFrmConfig_Gaveta in 'ncaFrmConfig_Gaveta.pas' {FrmConfig_Gaveta},
  ncaFrmEstado in 'ncaFrmEstado.pas' {FrmEstado},
  ncaFrmImpOrcamento in 'ncaFrmImpOrcamento.pas' {FrmImprimeOrcamento},
  ncaFrmToken in 'ncaFrmToken.pas' {FrmToken},
  ncaFrmInutilizarNFCe in 'ncaFrmInutilizarNFCe.pas' {FrmInutilizarNFCe},
  ncaFrmNCMPesq in 'ncaFrmNCMPesq.pas' {FrmNCMPesq},
  ncaDMSyncDoc in 'ncaDMSyncDoc.pas' {dmDocUpdate: TDataModule},
  ncaFrmReajustePreco in 'ncaFrmReajustePreco.pas' {FrmReajustePreco},
  ncaFrmPesqTranspEnt in 'ncaFrmPesqTranspEnt.pas' {FrmPesqTranspEnt},
  ncaFrmBRTrib_nfe in 'ncaFrmBRTrib_nfe.pas' {FrmBRTrib_nfe},
  ncaFrmConfig_Pais in 'ncaFrmConfig_Pais.pas' {FrmPais},
  ncaStrings in 'ncaStrings.pas',
  ncaFrmEmailUsuario in 'ncaFrmEmailUsuario.pas' {FrmEmailUsuario},
  ncaFrmAutoInc in 'ncaFrmAutoInc.pas' {FrmAutoInc},
  ncafbNFe in 'ncafbNFe.pas' {fbNFe: TFrmBasePai},
  ncaFrmConfig_NFE in 'ncaFrmConfig_NFE.pas' {FrmConfig_NFE},
  ncaFrmNFCeDepend in 'ncaFrmNFCeDepend.pas' {FrmNFCeDepend},
  ncaFrmEndereco in 'ncaFrmEndereco.pas' {FrmEndereco},
  ncEndereco in '..\comp\ncEndereco.pas',
  ncaFrmEnderecos in 'ncaFrmEnderecos.pas' {FrmEnderecos},
  ncaFrmMemoEnd in 'ncaFrmMemoEnd.pas' {FrmMemoEnd},
  ncaFrmEditEntrega in 'ncaFrmEditEntrega.pas' {FrmEditEntrega},
  ncaFrmBRTribPesq in 'ncaFrmBRTribPesq.pas' {FrmBRTribPesq},
  ncaFrmConfig_EndLoja in 'ncaFrmConfig_EndLoja.pas' {FrmConfig_EndLoja},
  ncaFrmBRTrib in 'ncaFrmBRTrib.pas' {FrmBRTrib},
  ncafbVendas2 in 'ncafbVendas2.pas' {fbVendas2: TFrmBasePai},
  ncTipoTran in '..\comp\ncTipoTran.pas',
  ncafbNFCupom in 'ncafbNFCupom.pas' {fbNFCupom: TFrmBasePai},
  ncafbProdEst in 'ncafbProdEst.pas' {fbProdEst: TFrmBasePai},
  ncaFrmConsumidor in 'ncaFrmConsumidor.pas' {FrmConsumidor},
  ncDMdanfe_NFCE in '..\comp\ncDMdanfe_NFCE.pas' {dmDanfe_NFCE: TDataModule},
  ncaFrmConfigDanfe_NFCe in 'ncaFrmConfigDanfe_NFCe.pas' {FrmConfigDanfe_NFCe},
  ncaFrmNFCeMigrarProd in 'ncaFrmNFCeMigrarProd.pas' {FrmNFCeMigrarProd},
  panModoHomoNFe in 'panModoHomoNFe.pas' {panAlertaModoHomoNFe: TFrame},
  panModoHomo in 'panModoHomo.pas' {panAlertaModoHomo: TFrame},
  ncaFrmNFCeModoHomo in 'ncaFrmNFCeModoHomo.pas' {FrmNFCeModoHomo},
  ncaFrmTipoNF in 'ncaFrmTipoNF.pas' {FrmTipoNF},
  ncaFrmMVAPauta in 'ncaFrmMVAPauta.pas' {FrmMVAPauta},
  ncaFrmImpDemDeb in 'ncaFrmImpDemDeb.pas' {FrmImpDemDeb},
  ncaFrmObs in 'ncaFrmObs.pas' {FrmObs},
  ncaFrmCancOk in 'ncaFrmCancOk.pas' {FrmCancOk},
  ncaFrmRejCanc in 'ncaFrmRejCanc.pas' {FrmRejCanc},
  ncafbCCE in 'ncafbCCE.pas' {fbCCE: TFrmBasePai},
  ncaFrmEntrega in 'ncaFrmEntrega.pas' {FrmEntrega},
  ncaFrmPesqEndereco in 'ncaFrmPesqEndereco.pas' {FrmPesqEndereco},
  ncaFrmCadFornecedor in 'ncaFrmCadFornecedor.pas' {FrmCadFornecedor},
  ncaFrmTrial_fim in 'ncaFrmTrial_fim.pas' {FrmTrial_fim},
  ncaFrmTrial_Sombra in 'ncaFrmTrial_Sombra.pas' {FrmTrial_sombra};

{$R *.res}
{---$R uac.res}

begin
  Application.Initialize;
  gGuardSide := False;
  NomeArqDebug := 'DebugNexAdmin.txt';
  
  Application.Title := 'NexAdmin';
  LadoServidor := False;

{  FormatSettings.CurrencyDecimals := 2;
  dxFormatSettings.CurrencyDecimals := 2;
  cxFormatController.CurrencyFormat := 'R$ ,0.00;-R$ ,0.00';}
  
  
  Application.CreateForm(TDados, Dados);
  Application.CreateForm(TdmImagens, dmImagens);
  Application.CreateForm(TdmImgEsp, dmImgEsp);
  Application.CreateForm(TFrmPri, FrmPri);
  Application.CreateForm(TFrmLocalizaCli, FrmLocalizaCli);
  Application.CreateForm(TFrmPanTopo, FrmPanTopo);
  Application.CreateForm(TFrmEmailUsuario, FrmEmailUsuario);
  Application.CreateForm(TFrmMVAPauta, FrmMVAPauta);
  Application.CreateForm(TfbCCE, fbCCE);
  Application.CreateForm(TFrmTrial_fim, FrmTrial_fim);
  Application.CreateForm(TFrmTrial_sombra, FrmTrial_sombra);
  Application.Run;
  Dados.Free;
  NomeArqDebug := '';
end.
